"""Format-agnostic markdown parser for skill and role files.

Extracts a normalized structure from either dotai or Claude-native format.
"""

import re
from pathlib import Path

from pydantic import BaseModel, Field


class ParsedArtifact(BaseModel):
    """Normalized representation of a parsed skill or role file."""

    name: str = ""
    description: str = ""
    entity_type: str = "unknown"  # "skill" or "role"
    format: str = "unknown"  # "dotai-skill", "dotai-role", "claude-native", "unknown"

    # Shared
    tags: list[str] = Field(default_factory=list)

    # Skill fields
    steps: list[str] = Field(default_factory=list)
    inputs: list[dict] = Field(default_factory=list)
    examples: list[str] = Field(default_factory=list)
    gotchas: list[str] = Field(default_factory=list)
    trigger: str = ""
    category: str = ""
    allowed_tools: list[str] = Field(default_factory=list)

    # Role fields
    persona: str = ""
    principles: list[str] = Field(default_factory=list)
    anti_patterns: list[str] = Field(default_factory=list)

    # Raw
    raw_body: str = ""
    sections: dict[str, str] = Field(default_factory=dict)
    frontmatter: dict[str, str] = Field(default_factory=dict)

    file_path: Path | None = None


def _strip_details_blocks(body: str) -> str:
    """Remove <details>...</details> blocks from body.

    These contain embedded role definitions in Claude Code SKILL.md files
    and should not influence format detection or content extraction.
    """
    return re.sub(r"<details>.*?</details>", "", body, flags=re.DOTALL).strip()


def detect_format(path: Path) -> str:
    """Detect file format: dotai-skill, dotai-role, claude-native, or unknown."""
    if not path.exists():
        return "unknown"

    if path.is_dir():
        if (path / "SKILL.md").exists():
            return "claude-native"
        if (path / "main.md").exists():
            return "dotai-skill"
        return "unknown"

    content = path.read_text()
    fm = _extract_frontmatter(content)
    body = _extract_body(content)

    # Claude Code auto-generated SKILL.md (has argument-hint or Auto-generated marker)
    if "argument-hint" in fm or "Auto-generated by dotai" in body:
        return "claude-native"

    # SKILL.md filename convention
    if path.name == "SKILL.md":
        return "claude-native"

    # Claude-native markers in frontmatter
    claude_keys = {"compatibility", "license"}
    if claude_keys & set(fm.keys()):
        return "claude-native"

    # dotai-skill markers in frontmatter
    dotai_skill_keys = {"trigger", "allowed-tools", "category"}
    if dotai_skill_keys & set(fm.keys()):
        return "dotai-skill"

    # dotai-skill markers in body
    if re.search(r"^## (Steps|Inputs)\b", body, re.MULTILINE):
        return "dotai-skill"

    # Strip <details> blocks before checking for role patterns — embedded roles
    # in skill files shouldn't trigger role detection
    clean_body = _strip_details_blocks(body)

    # dotai-role: has persona-like content + principles (outside <details>)
    if re.search(r"^## Principles\b", clean_body, re.MULTILINE) and re.search(r"^## Anti-patterns", clean_body, re.MULTILINE):
        return "dotai-role"

    # Role heuristics (persona without skill markers)
    if re.search(r"^You are a\b", clean_body, re.MULTILINE):
        return "dotai-role"

    return "unknown"


def parse_file(path: Path, force_format: str | None = None) -> ParsedArtifact:
    """Parse a skill or role file into a normalized structure.

    Args:
        path: Path to the file (or directory with SKILL.md/main.md)
        force_format: Override auto-detection
    """
    if path.is_dir():
        if (path / "SKILL.md").exists():
            actual_path = path / "SKILL.md"
        elif (path / "main.md").exists():
            actual_path = path / "main.md"
        else:
            return ParsedArtifact(file_path=path)
        return parse_file(actual_path, force_format)

    fmt = force_format or detect_format(path)
    content = path.read_text()
    fm = _extract_frontmatter(content)
    body = _extract_body(content)

    artifact = ParsedArtifact(
        file_path=path,
        format=fmt,
        frontmatter=fm,
        raw_body=body,
        name=fm.get("name", path.stem.replace("-", " ").replace("_", " ").title()),
        description=fm.get("description", ""),
        tags=_parse_list(fm.get("tags", "")),
    )

    if fmt in ("dotai-role",):
        artifact.entity_type = "role"
        _parse_role_body(artifact, body)
    elif fmt in ("dotai-skill", "claude-native", "unknown"):
        artifact.entity_type = "skill"
        _parse_skill_body(artifact, body, fm)

    # Skill-specific frontmatter
    if artifact.entity_type == "skill":
        artifact.trigger = fm.get("trigger", "")
        artifact.category = fm.get("category", "")
        artifact.allowed_tools = _parse_list(fm.get("allowed-tools", ""))

    return artifact


def _parse_skill_body(artifact: ParsedArtifact, body: str, fm: dict) -> None:
    """Extract skill sections from body."""
    # Strip <details> blocks (embedded role definitions in Claude Code SKILL.md)
    clean_body = _strip_details_blocks(body)
    sections = _split_sections(clean_body)
    artifact.sections = sections
    # Use clean body for raw_body so rubrics score the actual skill content
    artifact.raw_body = clean_body

    # Description: first content before any ## or # header in clean body
    desc_match = re.match(r"^(.*?)(?=^##? |\Z)", clean_body, re.DOTALL | re.MULTILINE)
    if desc_match:
        desc = desc_match.group(1).strip()
        if desc and not artifact.description:
            artifact.description = desc.split("\n\n")[0].strip()

    # Steps — capture numbered items with their continuation lines (sub-bullets)
    steps_body = sections.get("steps") or sections.get("workflow") or sections.get("instructions") or ""
    # Split on numbered items, keeping the full block for each step
    step_blocks = re.split(r"(?=^\d+\.\s)", steps_body, flags=re.MULTILINE)
    for block in step_blocks:
        block = block.strip()
        if not block:
            continue
        match = re.match(r"^\d+\.\s*(.+)", block, re.DOTALL)
        if match:
            # Join multi-line step into a single string, preserving sub-bullets
            step_text = match.group(1).strip()
            artifact.steps.append(step_text)

    # Inputs
    inputs_body = sections.get("inputs") or sections.get("parameters") or sections.get("arguments") or sections.get("configuration") or ""
    for match in re.finditer(r"-\s*`(\w+)`\s*(?:\((\w+)\))?\s*:?\s*(.+)", inputs_body):
        artifact.inputs.append({
            "name": match.group(1),
            "required": match.group(2) == "required" if match.group(2) else False,
            "description": match.group(3).strip(),
        })

    # Examples
    examples_body = sections.get("examples") or sections.get("usage") or ""
    for match in re.finditer(r"^-\s*(.+)$", examples_body, re.MULTILINE):
        artifact.examples.append(match.group(1).strip())

    # Gotchas
    gotchas_body = sections.get("gotchas") or sections.get("caveats") or sections.get("warnings") or sections.get("notes") or sections.get("limitations") or ""
    for match in re.finditer(r"^-\s*(.+)$", gotchas_body, re.MULTILINE):
        artifact.gotchas.append(match.group(1).strip())

    # Only fall back to body-wide numbered list extraction if we also found
    # other structured sections (inputs, examples, gotchas). Otherwise the
    # numbered items are likely content, not workflow steps.
    if not artifact.steps and (artifact.inputs or artifact.examples or artifact.gotchas):
        for match in re.finditer(r"^\d+\.\s*(.+)$", clean_body, re.MULTILINE):
            artifact.steps.append(match.group(1).strip())


def _parse_role_body(artifact: ParsedArtifact, body: str) -> None:
    """Extract role sections from body."""
    sections = _split_sections(body)
    artifact.sections = sections

    # Persona: everything before the first ## header
    persona_match = re.match(r"^(.*?)(?=^## |\Z)", body, re.DOTALL | re.MULTILINE)
    if persona_match:
        artifact.persona = persona_match.group(1).strip()
        if not artifact.description:
            # First sentence as description
            first_line = artifact.persona.split("\n")[0].strip()
            artifact.description = first_line[:200]

    # Principles
    principles_body = sections.get("principles") or ""
    for match in re.finditer(r"^-\s*(.+)$", principles_body, re.MULTILINE):
        artifact.principles.append(match.group(1).strip())

    # Anti-patterns
    anti_body = sections.get("anti-patterns (avoid these)") or sections.get("anti-patterns") or ""
    for match in re.finditer(r"^-\s*(.+)$", anti_body, re.MULTILINE):
        artifact.anti_patterns.append(match.group(1).strip())


def _split_sections(body: str) -> dict[str, str]:
    """Split markdown body into sections by ## headers."""
    sections: dict[str, str] = {}
    current_name = ""
    current_lines: list[str] = []

    for line in body.split("\n"):
        header_match = re.match(r"^##\s+(.+)$", line)
        if header_match:
            if current_name:
                sections[current_name] = "\n".join(current_lines).strip()
            current_name = header_match.group(1).strip().lower()
            current_lines = []
        else:
            current_lines.append(line)

    if current_name:
        sections[current_name] = "\n".join(current_lines).strip()

    return sections


def _extract_frontmatter(content: str) -> dict[str, str]:
    """Extract YAML-like frontmatter."""
    fm: dict[str, str] = {}
    if content.startswith("---"):
        parts = content.split("---", 2)
        if len(parts) >= 3:
            for line in parts[1].strip().split("\n"):
                if ":" in line:
                    key, value = line.split(":", 1)
                    fm[key.strip().lower()] = value.strip()
    return fm


def _extract_body(content: str) -> str:
    """Extract body after frontmatter."""
    if content.startswith("---"):
        parts = content.split("---", 2)
        if len(parts) >= 3:
            return parts[2].strip()
    return content.strip()


def _parse_list(raw: str) -> list[str]:
    """Parse comma-separated list."""
    return [item.strip() for item in raw.split(",") if item.strip()]
